---
- name: Play to create EC2 resources and finally a RHEL 8 instance.
  hosts: localhost
  vars:
    aws_region: us-east-2
    aws_instance_type: t2.micro
    aws_instance_rhel8_id: ami-0ba62214afa52bec7
    aws_instance_windows2019_id: ami-0c4a11a8d0e503812
    aws_instance_debian_id: ami-089fe97bc00bff7cc
    aws_instance_ubuntu_id: ami-0fb653ca2d3203ac1
    aws_key_pair_name: demo
    aws_client_name: myCompany

  tasks:
    - name: "1 - Task to create {{ aws_client_name }} VPC"
      amazon.aws.ec2_vpc_net:
        name: ansible_tower_vpc
        cidr_block: 10.10.0.0/16
        region: "{{ aws_region }}"
        tenancy: default
      register: ansible_tower_vpc

    - name: "2 - Create an Internet Gateway and associate to the {{ aws_client_name }} VPC"
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        state: present
      register: ansible_tower_igw

    - name: "3 - Create a subnet in the {{ aws_client_name }} VPC"
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        cidr: 10.10.0.0/20
        region: "{{ aws_region }}"
      register: ansible_tower_subnet

    - name: "4 - Set up public {{ aws_client_name }} subnet route table"
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        subnets:
          - "{{ ansible_tower_subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ ansible_tower_igw.gateway_id }}"

    - name: "5 - Task to create AWS security groups for {{ aws_client_name }}"
      amazon.aws.ec2_group:
        name: ansible_tower_sg
        description: AWS security group for Ansible Tower demostration
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 8080
              - 443
              - 3389
              - 5986
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all connections on port 22

    - name: "6 Provision RHEL8.4 nodes"
      amazon.aws.ec2:
        instance_type: "{{ aws_instance_type }}"
        image: "{{ aws_instance_rhel8_id }}"
        region: "{{ aws_region }}"
        count: "{{ number_of_rhels }}"
        wait: yes
        key_name: "{{ aws_key_pair_name }}"
        assign_public_ip: yes
        group: ansible_tower_sg
        vpc_subnet_id: "{{ ansible_tower_subnet.subnet.id }}"
        instance_tags:
          Name: RHEL8
          Type: Linux
