---
- name: Play to create EC2 resources and finally a RHEL 8 instance.
  hosts: localhost
  vars:
    aws_region: us-east-2
    aws_instance_type: t2.micro
    aws_instance_rhel8_id: ami-0ba62214afa52bec7
    aws_key_pair_name: demo

  tasks:
    - name: Crear instancia EC2
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: demo
        vpc_subnet_id: vpc-08e7d6ad108058415
        instance_type: t2.micro
        network:
          assign_public_ip: true
        image_id: ami-0ba62214afa52bec7
        tags:
          Name: RHEL8
          Type: Linux