---
- name: Upgrade and Reboot RHEL & Debian family Linux distros
  hosts: all
  vars:
    reboot_connect_timeout: 5
    reboot_post_reboot_delay: 15
    reboot_timeout: 600
  tasks:
    # Upgrade RHEL family OS packages
    - name: Upgrade RHEL Family OS packages
      yum:
        name: '*'
        state: latest
