---
- hosts: "{{ host }}"
  become: true
  tasks:
    - name: install podman
      shell: |
        podman pull registry.fedoraproject.org/f29/httpd

    - name: install podman
      shell: |
        podman run -dt -p 8080:8080/tcp registry.fedoraproject.org/f29/httpd
